= Zeiterfassung für Gruppe 01

Notieren Sie die Zeit in Minuten für jeden Entwickler und – getrennt davon – für Team-Treffen pro Woche (Wochengranularität).
Die individuell erfasste Zeit beinhaltet auch das Lesen von Dokumentationen, Besprechungen mit Teamkollegen und sonstige auf das Praktikum bezogene Aufgaben, jedoch *nicht* das Team-Treffen (= letzte Spalte).

// See http://asciidoctor.org/docs/user-manual/#tables
[option="headers"]
|===
|Woche |Aron |Max |Cornell |Willy |Bruno |Meeting
|1  |180   |180    |120    |180    |180   |45       
|2  |120   |200    |160   |120    |960    |45
|3  |1230   |1080    |1260    |900    |1080    |60    
|4  |870   |720    |600   |540    |660    |30    
|5  |2200   |600    |360    |1400    |1560   |15 
|6  |720   |660    |720    |720   |600 |20
|7  |900   |720    |900    |900    |1020    |70    
|8  |1200   |1080    |600    |1200   |480    |75     
|9  |1080   |960    |1200    |1000    |1320    |40       
|10  |570   |780    |420    |500    |1020    |60      
|11  |600   |500    |480    |500    |1080  |35      
|12  |1500   |1320    |2040    |1400    |1440    |80       
|SUM|11170||||
|AVERAGE|930.8||||
|===

Bitte tragen Sie am Ende des Praktikums noch folgende weitere Werte ein:
Summe der Arbeitsstunden pro Student:

SUMME(SPALTE(DevX))

Arbeitsstunden pro Woche pro Student:

SUMME(SPALTE(DevX)) / 12

Durchschnittliche Arbeitzeit aller Studenten pro Woche:

(SUMME(SPALTE(Dev1)) + SUMME(SPALTE(Dev2)) + SUMME(SPALTE(Dev3)) + SUMME(SPALTE(Dev4)) + SUMME(SPALTE(Dev5)) +SUMME(SPALTE(Dev6))) / 6
