= Persönliches Feedback eines Teammitgliedes des Softwarepraktikums 2017/18
// Auch wenn der Bogen nicht anonymisiert ist, dürfen Sie gern Ihre Meinung offen kundtun.
// Sowohl positive als auch negative Anmerkungen werden gern gesehen und zur stetigen Verbesserung genutzt.
// Versuchen Sie in dieser Auswertung also stets sowohl Positives wie auch Negatives zu erwähnen.

**Von:**
Bruno Reinhold +
**Gruppe:**
SWT18/01 +

== Was habe ich gelernt?
// Ausführung der positiven und negativen Erfahrungen, die im Softwarepraktikum gesammelt wurden
-> Umsetzung eines echten Software-Projekts von Analyse über Entwurf bis Implementierung  +
-> Fokussieren auf das für die Erfüllung der Aufgabe wesentliche (nicht in Details verlieren) +
-> Protokollierung der Projekttreffen (Festhalten von Fakten, Entscheidungen und Terminen)  +
-> Akzeptieren des dynamischen Projektverlaufes (Interpretation der Aufgaben immer wieder verfeinern um diese effizient umsetzten zu können) +
Allgemein muss ich sagen das Praktikum war fördernd aber auch sehr fordernd, denn als externe Gruppe mussten wir einige neue Technologien lernen.
Mangels Vorkenntnissen war das mitunter sehr zeitintensiv und frustirent. Es ließ sich allerdings immer rechtzeitig eine entsprechende Lösung finden, was am Ende des Sprints neue Motivation für den nächsten Sprint geliefert hat. +

== Welche Erfahrungen habe ich mit der Zusammenarbeit im Team gemacht?
// Kurze Beschreibung der Zusammenarbeit im Team. Was lief gut? Was war verbesserungswürdig? Was würden Sie das nächste Mal anders machen?
Aus meiner Perspektive hat jeder Einzelen im Team das Projekt sehr ernst genommen. Der Arbeitsaufwand wurde möglichst gerecht verteilt.
Kommunikation ist der Schlüssel für erfolgreiche Zusammenarbeit. Im Team haben wir unter der Nutzung von Telegram, Slack und Discord
eine direkte und schnelle Kommunikation etabliert. Über den gesamten Zeitraum des Projekts waren so alle Teammitglieder erreichbar,
was sicher besonders zum kontinuierlichen Vortschritt des Projekts beigetragen hat. Trotz oder grade wegen der verschiedenen Kommunikationskanäle ist zum Teil,
die ein oder andere Nachricht untergegangen. Die Protokolle boten eine Möglichkeit den Überblick über das Projekt zu behalten, diese Möglichhkeit hätten wir im Team noch besser wahrnehmen können. +


== Welche Erfahrungen habe ich bei der Wiederverwendung von Bibliotheken/Frameworks (insbesondere SalesPoint) gemacht?
// Einschätzung der Arbeit mit den bereitgestellten und zusätzlich genutzten Frameworks. Was War gut? Was war verbesserungswürdig?
Während der Implementierung habe ich am Python-Backend entwickelt. Ich war vorrangig für die Kommunikation mit dem Active Directory zuständig. Dafür habe ich die Python-Bibliothek ldap3 verwendet. +

== Welche Vorschläge zur weiteren Verbesserung des Softwarepraktikums gibt es?
// Möglichst mit Beschreibung, warum die Umsetzung des von Ihnen angebrachten Vorschlages nötig ist.
Als Mitglied einer externen Gruppe, hatte ich vor allem wären der Analysephase und der Entwurfsphase das Gefühl,
 dass die Aufgaben/Vorgaben der internen Gruppen mit unseren kollidieren.
 Des Weiteren finde ich es nicht sinnvoll einfach alle Analysemethoden durchzuexerzieren, selbst wenn sie auf unsere Aufgabe bezogen, nur einen sehr geringen Mehrwert bieten.
 Die so gewonnen Zeit hätte man in einen besseren Entwurf der Datenstrukturen investieren können, was uns gegen Ende des Projektes viel Zeit gespart hätte.
 Streckenweise war der Arbeitsaufwand für das gesammte Team sehr hoch, vielleicht hätte hier ein weiteres Teammitglied für Entlastung sorgen können.
 Aus Fehlern lernt man, deshalb hätten man vielleicht noch mehr Wert auf die Sprint-Retrospective legen können. +

== Feedback für den Tutor
// Fühlten Sie sich durch den vom Lehrstuhl bereitgestellten Tutor gut betreut? Was war positiv? Was war verbesserungswürdig?
Paul hat uns auf dem Weg durch das Praktikum immer rechtzeitig über Termine und Entscheidungen seitens des Lehrstuhls informiert.
Des Weiteren hat er uns, während des Praktikums viel Freiraum gelassen was die Ausführung der Aufgaben angeht.
Trotz kleinerer Missverständnisse bin ich sehr zufrieden. +

== Sonstiges und Anmerkungen
// Welche Aspekte fanden in den oben genannten Punkten keine Erwähnung?
