= Persönliches Feedback eines Teammitgliedes des Softwarepraktikums 2017/18
// Auch wenn der Bogen nicht anonymisiert ist, dürfen Sie gern Ihre Meinung offen kundtun.
// Sowohl positive als auch negative Anmerkungen werden gern gesehen und zur stetigen Verbesserung genutzt.
// Versuchen Sie in dieser Auswertung also stets sowohl Positives wie auch Negatives zu erwähnen.

**Von:**

**Gruppe:**

== Was habe ich gelernt?
Im Verlauf des Projektes habe ich sehr viel über das Kreieren von Software im Allgemeinem gelernt. + 
Die Analysephase ist für mich nun verständlicher bzw. sinnvoller, als sie es davor war und trotz der Umstände, welche z.B. Zustandsdiagramme bereiten, wirken diese nun nötig und die Mühe wert. + 
Meine Aufgabe war im wesentlichen, das Erstellen und Verwalten der Datenbank sowie das Ausarbeiten einer Schnittstelle zu dieser. Ich habe viel über MySQL-Datenbanken im Allgemeinen gelernt (Was ist möglich?Was eher nicht?) und das Prinzip eines ORMs, was mir kein Begriff war, nun verstanden. MySQLAlchemy war mir am Start des Praktikums sehr fremd und kam mir mehr oder weniger kryptisch vor. Nach einiger Zeit habe ich es aber Verstehen und Nutzen gelernt, und ich denke, ich kann mittlerweile behaupten mich zumindest mit den Grundlagen eines ORMs nun sehr gut auszukennen. +
Auch wenn es nicht 100%ig meinen Aufgabenbereich betraf, verstehe ich jetzt das Prinzip von Flask und REST-Schnittstellen. Testen von Code, womit ich vor dem Praktikum kaum Erfahrung hatte ist für mich nun möglich, wobei ich hier noch Defizite  habe. + 
Während des Softwarepraktikums habe ich viel über Team-Dynamik aber auch über das Arbeiten als Entwickler mit einem Kunden gelernt Auch das Dokumentieren und Verständlichmachen von Code fällt mir nun leichter.  
// Ausführung der positiven und negativen Erfahrungen, die im Softwarepraktikum gesammelt wurden

== Welche Erfahrungen habe ich mit der Zusammenarbeit im Team gemacht?
Am Anfang muss ich leider anmerken, dass mein Zeitmanagement und meine Auslegung von Deadlines zu Beginn des Projektes zu Problemen geführt haben. Da ich Aufgaben kurz vor der Abgabe erledigt hatte, war es für andere Teammitglieder nicht möglich diese zu reflektieren und zu verbessern. +
Ich war sehr zufrieden mit meinem Team, da jeder von ihnen von Anfang an voll bei der Sache war und sich im Verlauf des Praktikums als sehr zuverlässig und kompetent erwiesen hat. Das Aufteilen auf verschiedene Bereiche, hat jeden, im Vergleich mit den anderen Teammitgliedern, zu einem Spezialisten auf einem bestimmten Gebiet gemacht. Meist ließen sich Probleme durch Diskussion mit dem ganzen Team klären, da jeder einen anderen Blickwinkel auf Sachverhalte hatte. + 
Die kommunikation hat Teamintern sehr gut funktioniert. Slack, Telegramm und Diskord waren nützliche Technologien zur Verständigung. Ich finde, dass das Aufteilen von Aufgaben fair und durchdacht abgelaufen ist. + 
Bei meiner nächsten Gruppenarbeit würde ich Aufgaben preventief besser Absprechen und Deadlines (privat sowie im Team) eher angehen. +
Verbesserungswürdig fand ich die Produktivität mancher teaminterner Treffen, was jedoch finde ich normal ist.
// Kurze Beschreibung der Zusammenarbeit im Team. Was lief gut? Was war verbesserungswürdig? Was würden Sie das nächste Mal anders machen?

== Welche Erfahrungen habe ich bei der Wiederverwendung von Bibliotheken/Frameworks (insbesondere SalesPoint) gemacht?
Ich habe im Python-Backend gearbeitet. Die von mir benutzen Bibliotheken/Frameworks waren Flask und SQLAlchemy.
// Einschätzung der Arbeit mit den bereitgestellten und zusätzlich genutzten Frameworks. Was War gut? Was war verbesserungswürdig?

== Welche Vorschläge zur weiteren Verbesserung des Softwarepraktikums gibt es? 
Als externer Praktikumsabsolvent hatte ich das Gefühl, dass vieles im Praktikum auf das interne Praktikum ausgelegt war. Es gab z.B. viele Analyse-Anforderungen welche sich als unbrauchbar für uns herausstellten. + 
Auch sollten meiner Meinung nach, neue Technologien auf irgendeine Art und Weise eingeführt werden, da man sich am Anfang des Praktikums ein wenig das Gefühl hatte, ins kalte Wasser geworfen worden zu sein.
// Möglichst mit Beschreibung, warum die Umsetzung des von Ihnen angebrachten Vorschlages nötig ist.

== Feedback für den Tutor
Unser Tutor, Paul, war immer zuverlässig und hilfsbereit. Es war immer sehr sinnvoll neue Ideen erst mit Paul abzusprechen, da dieser meist Verbesserungsvorschläge sowie Vorschläge zur Umsetztung hatte. + 
Ich bin sehr zufrieden.
// Fühlten Sie sich durch den vom Lehrstuhl bereitgestellten Tutor gut betreut? Was war positiv? Was war verbesserungswürdig?

== Sonstiges und Anmerkungen
Der Zeitaufwand zum erreichen einiger Deadlines standen für mich manchmal in keinem Verhältniss zum eigentlichen Zeitrahmen des Projekts. + 
Auch fand ich die Kommunikation zum Kunden 3m5 zur Zeit der Pflichtenheftabgabe zu wenig. Es ist für mich selbstverständlich, dass die Betreuer von 3m5 selbst einen Berufsalltag haben und uns nicht wegen jeder Kleinigkeit hinterher rennen können. Ich hätte mir jedoch mehr Kommunikation zum "Kunden" gewünscht, da es im Verlauf des Praktikums ab und zu Meinungsverschiedenheiten zur Funktion der Anwendung gab. + Dies ist jedoch meiner Meinung nach ein gutes Beispiel für das Arbeiten als Softwareentwickler. Zum Ende unseres Projektes hat die Absprache jedoch einwandfrei funktioniert. 
// Welche Aspekte fanden in den oben genannten Punkten keine Erwähnung?