= Persönliches Feedback eines Teammitgliedes des Softwarepraktikums 2017/18
// Auch wenn der Bogen nicht anonymisiert ist, dürfen Sie gern Ihre Meinung offen kundtun.
// Sowohl positive als auch negative Anmerkungen werden gern gesehen und zur stetigen Verbesserung genutzt.
// Versuchen Sie in dieser Auswertung also stets sowohl Positives wie auch Negatives zu erwähnen.

**Von:**
Maximilian Schaller

**Gruppe:**
swt18w1

== Was habe ich gelernt?
// Ausführung der positiven und negativen Erfahrungen, die im Softwarepraktikum gesammelt wurden
Ich habe einen guten Einblick in die Realität der Softwareentwicklung bekommen, wie schwierig es werden kann Zeiten die man braucht richtig abzuschätzen, um Deadlines pünktlich zu schaffen, wie viel eine gute Vorbereitung (Analyse) ausmachen kann und wie sehr die Realität von der Theorie der Softwareentwicklung abweicht und man Probleme (zum Beispiel Kundenwünsche) noch möglichst schnell umsetzen muss.

Außerdem habe ich mich intensiv mit vielen neuen Technologien auseinandersetzen müssen bzw habe diese kenengelernt (zB: Javascript, React, Redux, Docker, Datenbanken, ...)


== Welche Erfahrungen habe ich mit der Zusammenarbeit im Team gemacht?
// Kurze Beschreibung der Zusammenarbeit im Team. Was lief gut? Was war verbesserungswürdig? Was würden Sie das nächste Mal anders machen?

Die Aufteilung der Aufgaben und das jeder wirklich sein Zeug gemacht,wie er konnte, engagiert war und keiner die Gruppe hängen lies, klappte bei uns zum größten Teil sehr gut.

Bei nächsten mal hätte man manche Aufgaben nicht bis zum letzten Moment herauszögern müssen, wobei sich das während des Praktikums auch verbesserte.

== Welche Erfahrungen habe ich bei der Wiederverwendung von Bibliotheken/Frameworks (insbesondere SalesPoint) gemacht?
// Einschätzung der Arbeit mit den bereitgestellten und zusätzlich genutzten Frameworks. Was War gut? Was war verbesserungswürdig?

Alle Bibliotheken die ich genutzt habe, habe ich komplett neu kennengelernt. Vorallem habe ich mit der Javascript-Library "React" gearbeitet, was gleichzeitig mein Einstieg in die Frontend-Entwicklung und meine erste Erfahrung mit Javascript waren. 

Da ich in möglichst kurzer Zeit viel neues Lernen musste, fehlte mir leider die Zeit die neue Technologie richtig zu verstehen und nicht bloß sie zu benutzen.

== Welche Vorschläge zur weiteren Verbesserung des Softwarepraktikums gibt es?
// Möglichst mit Beschreibung, warum die Umsetzung des von Ihnen angebrachten Vorschlages nötig ist.

Die Aufgaben (insb. externes Praktikum) kleiner halten, bzw darauf achten, dass nicht all zu viele neuen Technologien gelernt werden müssen. Auch wenn wir uns bewusst für das externe Praktikum eingeschrieben haben, hat jeder noch andere Module zu bestehen und noch ein Leben außerhalb der Uni, was teilweise sehr unter dem Praktikum leiden musste.


== Feedback für den Tutor
// Fühlten Sie sich durch den vom Lehrstuhl bereitgestellten Tutor gut betreut? Was war positiv? Was war verbesserungswürdig?
Ich denke wir haben schon sehr selbstständig gearbeitet und die Fragen die wir hatten konnte unser Tutor zum größten Teil klären. Da wir keine größeren Probleme hatten, war alles soweit in Ordnung.

== Sonstiges und Anmerkungen
// Welche Aspekte fanden in den oben genannten Punkten keine Erwähnung?


