= Entwicklerdokumentation

== Einführung und Ziele
* Aufgabenstellung
Erstellen einer Flask-App, welche mit einer MySQL-Datenbank kommuniziert. Es soll möglich sein Daten aus der Datenbank auszulesen, sowie Daten einzutragen.
Befehle zum Auslesen/Eingeben von Daten sollen über eine REST-Schnittstelle erfolgen.

* Qualitätsziele
-Datenübergabe über REST-Punkt, welche dann auf der Datenbank gespeichert werden.
-Datenabfrage über REST-Punkt, welche dann von der Datenbank extraiert werden.

== Randbedingungen
* Hardware-Vorgaben +
Rechner, der einen Webserver und eine Datenbank laufen lassen kann. 
(es reicht kein Raspberry Pi)
* Software-Vorgaben +
flask, mysql, flask-mysqldb, Flask-App, MySQL-Datenbank


* Vorgaben zum Betrieb des Software +
Port Anpassungen für mySQL (Hauptsächlich Port 80, welcher standardmäßig von Skype besetzt ist)
Verbindung der Flask-App mit MySQL-Datenbank

== Kontextabgrenzung
* Externe Schnittstellen +
-REST-Punkt

== Lösungsstrategie
Die Flask-Anwendung wird mit der MySQL-Datenbank verbunden.
Die REST-Schnittstelle ruft entweder POST oder GET-Funktionen in der Flaks-Anwendung auf. Die POST-Funktion schreibt Daten auf die Datenbank, Die GET-Funktion ließt Daten aus und gibt diese über die REST-Schnittstelle weiter.


== Bausteinsicht
* Package-Diagramme +


== Entwurfsentscheidungen
* Architektur
* Verwendete Muster
* Persistenz +
 -Die Datenbank darf nicht abgeschaltet werden.
* Benutzeroberfläche 


[appendix]
== Glossar
* Flask +
Python-Framework.

* MySQL +
Datenbank-Typ.
