= Erklärung von prototypebezogenen Fachbegriffen

== LDAP ==
*-> Lightweight-Directory-Access-Protocol* +
Dabei handelt es sich um ein Netzwerkprotokoll. Es setzt sich aus einem Client-Sever-Modell zusammen, welches die Kommunikation mit einem externen Directory-Services ermöglicht. 
Ziel der abfragebasierten Kommunikation ist die Abfrage bzw. Veränderung von Informationen im Directory-Services. +

== DIT ==
*-> Directory-Information-Tree* +
Der Directory-Services besteht aus einem Directory-Information-Tree. Der DIT setzt sich wiederum aus hierarchisch strukturierten Schlüssel-Wert-Paaren zusammen, welche mittels des LDAP verwaltet werden können. 

== LDAP-Binding-String == 
Der LDAP-Binding-String ermöglicht den Zugriff auf ein Objekt in der Hierarchie. Das folgende Beispiel zeigt, dass der LDAP-Binging-String aus den Spezifikationen des Objektes besteht. +

*LDAP://CN=Joe Smith,OU=East,CN=users,DC=MyDomain,DC=com* +

Bedeutung der Abkürzung: +
[options="header"]

|===
|Abkürzung|Bedeutung
|cn |Common Name
|ou |Organizational Unit
|dc |Domain Component
|LDAP:|The provider (case sensitive)
|cn=Joe Smith,ou=East,dc=MyDomain,dc=net | Distinguished Name of user "Joe Smith"
|cn=Joe Smith | Relative Distinguished Name of user "Joe Smith"
|dc=MyDomain,dc=com| DNS domain name (MyDomain.com)
|cn=Users |Relative Distinguished Name of container "Users"
|ou=East|Organizational Unit where user "Joe Smith" resides
|===

== NTLM == 
*-> NT LAN Manager*
Dabei handelt es sich um ein Authentifizierungsverfahren, dass mittels Challenge-Response-Authentifizierung Benutzerinformationen überprüft.
Ablauf: 
1. Client sendet Benutzernamen
2. Server antwortet mit einer Zufallszahl (Challenge)
3. Client antwortet wiederum mit der Zufallszahl, die mit dem Hashwert des Benutzerpassworts verschlüsselte wurde (Response)
4. Server gleicht Response mit Informationen des Directory-Services
5. Server sendet nach erfolgreichem Abgleich Bestätigung 